#!bash

# ### ALIAS ###

# bash edit
alias bash_edit="subl ~/.bash"
alias bash_reload=". ~/.bash_profile"

# handy stuff
alias s="subl ."
# handy stuff
alias v="code ."

alias cd..='cd ..'
alias ..='cd ..'
alias c="clear"

alias t="yarn test"
alias l="yarn lint"

alias ls='ls -GFh'
alias ll="ls -al"

alias f='open -a Finder ./'

alias fix_pointer='git lfs uninstall && git reset --hard && git lfs install && git lfs pull'

mkcd() {
    mkdir $1
    cd $1
}

alias hosts_edit="subl /etc/hosts"

alias d="docker"
alias dp="docker ps"
alias dpa="docker ps --all"

# docker
dockerssh() {
  docker exec -it $1 bash
}
