#!bash

# ### ALIAS ###

# bash edit
alias bash_edit='(cd ~/.bash && code .)'
alias bash_reload=". ~/.bash_profile"

# vscode edit
alias v="code ."

alias cd..='cd ..'
alias ..='cd ..'

alias c="clear"

alias ls='ls -GFh'
alias ll="ls -al"

alias f='open -a Finder ./'

alias rmrf='rm -Rf'

mkcd() {
    mkdir $1
    cd $1
}