#!bash

# ### ALIAS ###

# bash edit
alias bash_edit="subl ~/.bash"
alias bash_reload=". ~/.bash_profile"

# handy stuff
alias s="subl ."

alias cd..='cd ..'
alias ..='cd ..'
alias c="clear"

alias t="yarn test"
alias l="yarn lint"

alias ls='ls -GFh'
alias ll="ls -al"

alias f='open -a Finder ./'

mkcd() {
    mkdir $1
    cd $1
}

alias hosts_edit="subl /etc/hosts"