#!bash

# ### COLORS ###

# console colors
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

bold=''
reset="\e[0;0m"
gray="\e[0;30m"
grayGlow="\e[1;30m"
grayGlow2="\e[0;20m"
red="\e[31m"
redGlow="\e[1;31m"
green="\e[0;32m"
greenGlow="\e[1;32m"
orange="\e[0;33m"
orangeGlow="\e[1;33m"
blue="\e[0;34m"
blueGlow="\e[1;34m"
pink="\e[0;35m"
pinkGlow="\e[1;35m"
turky="\e[0;36m"
turkyGlow="\e[1;36m"
signal="\e[1;37m"

PS1="\[${pink}\]\u" # user
PS1+="\[${grayGlow2}\]@" # @
PS1+="\[${turky}\]\h" # host
PS1+="\[${grayGlow2}\]: " # :
PS1+="\[${blue}\]\w" # path
PS1+="\[${orangeGlow}\] \$(parse_git_branch)" # git branch
PS1+="\n" # newline... no shit sherlock
PS1+="\[${pink}\]\$ " # $
PS1+="\[${reset}\]" #
export PS1
