#!bash

# ### COLORS ###

# console colors
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

bold=''
reset="\e[0m"
gray="\e[1;30m"
red="\e[31m"
redGlow="\e[1;31m"
green="\e[1;32m"
greenGlow="\e[32m"
orange="\e[33m"
orangeGlow="\e[1;33m"
blue="\e[34m"
blueGlow="\e[1;34m"
pink="\e[35m"
pinkGlow="\e[1;35m"
turky="\e[36m"
turkyGlow="\e[1;36m"
signal="\e[1;37m"

 PS1="\[${orange}\]\u" # user
PS1+="\[${turkyGlow}\]@" # @
PS1+="\[${green}\]\h" # host
PS1+="\[${turkyGlow}\]:" # :
PS1+="\[${blue}\]\W" # path
PS1+="\[${turkyGlow}\] \$(parse_git_branch)" # git branch
PS1+="\n" # newline... no shit sherlock
PS1+="\[${gray}\]\$ " # $
PS1+="\[${reset}\]" #
export PS1